# Generated by Django 4.2.11 on 2024-03-07 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('Back-end', 'Back-end'), ('Front-end', 'Front-end'), ('Outros', 'Outros')], max_length=20)),
                ('status', models.CharField(choices=[('On', 'On'), ('Off', 'Off')], max_length=5)),
                ('technology', models.CharField(max_length=50)),
                ('database', models.CharField(max_length=50)),
                ('project_url', models.URLField()),
                ('server_name', models.CharField(max_length=50)),
                ('server_ip', models.CharField(max_length=15)),
            ],
        ),
    ]
