# Generated by Django 4.2.11 on 2024-03-07 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_ambiente_alter_status_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='ambiente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.ambiente'),
        ),
        migrations.AlterField(
            model_name='ambiente',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
