# Generated by Django 4.2.11 on 2024-03-11 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_project_ambiente_alter_ambiente_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServidorIp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'IP do Servidor',
                'verbose_name_plural': 'IPs do Servidor',
            },
        ),
        migrations.CreateModel(
            name='ServidorName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Nome do Servidor',
                'verbose_name_plural': 'Nomes do Servidores',
            },
        ),
        migrations.AlterField(
            model_name='project',
            name='server_ip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.servidorip'),
        ),
        migrations.AlterField(
            model_name='project',
            name='server_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.servidorname'),
        ),
    ]
